version: '3'

services:
  mysql:
    image: mysql:8.0.23
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: 'test'
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: "mysqladmin ping -h localhost -u root || exit 1"
      interval: 1s
      timeout: 10s
      retries: 5
